CREATE PROCEDURE LARGE_SAL()
SELECT * 
FROM employee_salary
WHERE salary>50000;

CALL LARGE_SAL();

DELIMITER $$
CREATE PROCEDURE LARGE_SAL2()
BEGIN
SELECT * 
FROM employee_salary
WHERE salary>50000;
SELECT * 
FROM employee_salary
WHERE salary>10000;
END $$
DELIMITER ;

CALL LARGE_SAL2();

DELIMITER $$
CREATE PROCEDURE LARGE_SAL3(EMPID INT)
BEGIN
SELECT salary 
FROM employee_salary
WHERE employee_id=EMPID;

END $$
DELIMITER ;

CALL LARGE_SAL3(1);