CREATE TEMPORARY TABLE TEMP_TABLE
(
first_name VARCHAR(50),
last_name VARCHAR(50),
favorite_movie VARCHAR(50)
);

INSERT INTO TEMP_TABLE
VALUES('SAFAL','BEHERA','INTERSTELLER');

SELECT * 
FROM TEMP_TABLE;



CREATE TEMPORARY TABLE SAL_OVER_50K
SELECT *
FROM employee_salary
WHERE salary>50000;


SELECT *
FROM SAL_OVER_50K;